### ISSUE TITLE
PIN Üben => Farbe bleibt bestehen

### ISSUE THREAD

**Issue by krisbr** [SecUSo/privacy-friendly-pin-mnemonic#10]
Wenn man die PIn übt und die PIN falsch/richtig eingibt (vier Zahlen), dann Reset klickt und die PIN erneut eingibt, dann sind alle Zahlen bei der Eingabe schon grün/rot.

**Comment by Yonjuni** [comment]
Konnte ich nicht reproduzieren. Welche Version hast du genutzt? Das war nämlich mal ein Problem in einer älteren.

**Comment by krisbr** [comment]
Achso, die aktuelle aus dem PlayStore. Sonst habe ich keine gefunden.

**Comment by Yonjuni** [comment]
Closed #10
