### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [SecUSo/privacy-friendly-pin-mnemonic#14]
Hi @SecUSo

I found [this app](https://play.google.com/store/apps/details?id=co.DarkSlateGray.privacyfriendlypin) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app.

**Comment by Yonjuni** [comment]
@Poussinou How do you search for those copies? What's your approach?

**Comment by Poussinou** [comment]
The app is down now. 
I'll close this issue but do not hesitate to reopen it if you find another one! :)
