### ISSUE TITLE
Unscharfe Bilder

### ISSUE THREAD

**Issue by krisbr** [SecUSo/privacy-friendly-pin-mnemonic#9]
Bei den Einstellungen unter "Form" sind die Bilder auf einem FullHD Gerät unscharf

**Comment by Yonjuni** [comment]
Welche (physische) Displaygröße hast du verwendet?

**Comment by krisbr** [comment]
5.5 Zoll mit Full HD(1920 x 1080 pixels), 401 PPI

**Comment by Yonjuni** [comment]
Closed #9
